package com.zebwqfox.hbustpower.data

import com.zebwqfox.hbustpower.HandoffFixtures
import com.zebwqfox.hbustpower.model.MeterKind
import com.zebwqfox.hbustpower.stringOrNull
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.time.Instant

/**
 * Every expectation here comes from `fixtures/expected-1.7.1.json`, which `tools/ios-parser-harness`
 * generated by running the iOS 1.7.1 parser over the same samples.
 */
class ElectricityHtmlParserTest {
    private val parser = ElectricityHtmlParser()
    private val fetchedAt = Instant.parse("2026-09-07T03:00:00Z")

    @Test fun parsesLegacyFixtures() {
        val expected = HandoffFixtures.expected.getAsJsonObject("legacy")
        val snapshot = parser.parse(
            HandoffFixtures.html("home.html"),
            HandoffFixtures.html("usage.html"),
            HandoffFixtures.html("records.html"),
            fetchedAt,
        )
        assertEquals(expected.get("room").asString, snapshot.room)
        assertEquals(expected.get("purchasedKWh").asDouble, snapshot.purchasedKWh, 0.0001)
        assertEquals(expected.get("subsidyKWh").asDouble, snapshot.subsidyKWh!!, 0.0001)
        assertEquals(expected.get("unitPrice").asDouble, snapshot.unitPrice!!, 0.0001)
        assertEquals(expected.get("usageCount").asInt, snapshot.usageRecords.size)
        assertEquals(expected.get("rechargeCount").asInt, snapshot.rechargeRecords.size)
        assertEquals(expected.get("lightingAverage").asDouble, snapshot.recentAverage(MeterKind.LIGHTING)!!, 0.0001)
        assertEquals(
            expected.get("acAverage").asDouble,
            snapshot.recentAverage(MeterKind.AIR_CONDITIONING)!!,
            0.0001,
        )
        assertEquals(expected.get("predictedDays").asDouble, snapshot.predictedDays!!, 0.0001)
        assertMeters(expected, parser.meters(HandoffFixtures.html("home.html")))
    }

    /** A normal page whose footer merely mentions 统一身份认证 must not read as a signed-out session. */
    @Test fun treatsFooterAuthenticationMentionAsSignedIn() {
        val expected = HandoffFixtures.expected.getAsJsonObject("homeFooterAuth")
        val html = HandoffFixtures.html("home-footer-auth.html")

        assertEquals(expected.get("isLoginPage").asBoolean, parser.isLoginPage("https://ecard.hbust.edu.cn/pay/home", html))
        assertEquals(expected.get("isLoginPlaceholder").asBoolean, parser.isLoginPlaceholder(html))
        assertEquals(expected.get("room").asString, parser.room(html))
        assertEquals(expected.get("purchasedKWh").asDouble, parser.purchasedKWh(html)!!, 0.0001)
        assertEquals(expected.get("subsidyKWh").asDouble, parser.subsidyKWh(html)!!, 0.0001)
        assertEquals(expected.get("unitPrice").asDouble, parser.unitPrice(html)!!, 0.0001)
        assertMeters(expected, parser.meters(html))
    }

    @Test fun detectsLoginPages() {
        assertTrue(parser.isLoginPage("https://ecard.hbust.edu.cn/pay/home", HandoffFixtures.html("login-form.html")))
        assertTrue(parser.isLoginPage("https://ecard.hbust.edu.cn/Login?next=1", ""))
        assertTrue(parser.isLoginPage("https://ecard.hbust.edu.cn/pay/home", "Session过期，请重新进入"))

        // Script-rendered: not a login form yet, but the home page has lost its balance.
        val rendered = HandoffFixtures.html("login-script-rendered.html")
        assertFalse(parser.isLoginPage("https://ecard.hbust.edu.cn/pay/home", rendered))
        assertTrue(parser.isLoginPlaceholder(rendered))
    }

    /** A record missing a field shows `-` rather than borrowing the next record's value. */
    @Test fun keepsRecordFieldsWithinTheirOwnRecord() {
        val expectedUsage = HandoffFixtures.expected.getAsJsonArray("usageMissingFields")
        val usage = parser.usageRecords(HandoffFixtures.html("usage-missing-fields.html"))
        assertEquals(expectedUsage.size(), usage.size)
        expectedUsage.forEachIndexed { index, element ->
            val expected = element.asJsonObject
            val actual = usage[index]
            assertEquals(expected.get("dateEpoch").asLong, actual.occurredAt.epochSecond)
            assertEquals(expected.get("kWh").asDouble, actual.kWh, 0.0001)
            assertEquals(expected.get("meterName").asString, actual.meterName)
            assertEquals(expected.get("kind").asString, actual.kind.label)
        }

        val expectedRecharge = HandoffFixtures.expected.getAsJsonArray("recordsMissingFields")
        val recharge = parser.rechargeRecords(HandoffFixtures.html("records-missing-fields.html"))
        assertEquals(expectedRecharge.size(), recharge.size)
        expectedRecharge.forEachIndexed { index, element ->
            val expected = element.asJsonObject
            val actual = recharge[index]
            assertEquals(expected.get("dateEpoch").asLong, actual.occurredAt.epochSecond)
            assertEquals(expected.get("amountText").asString, actual.amountText)
            assertEquals(expected.get("kWhText").asString, actual.kWhText)
            assertEquals(expected.get("type").asString, actual.type)
            assertEquals(expected.get("meterName").asString, actual.meterName)
            assertEquals(expected.stringOrNull("studentNumber"), actual.studentNumber)
        }
    }

    /** School timestamps are Beijing time whatever the device's locale, calendar or zone. */
    /** iOS 1.8.2: the live page's title carries the first meter's type. */
    @Test fun roomTitleDropsTheMeterTypeSuffix() {
        assertEquals("东10-625", parser.room("""<li class="list-group-title">东10-625照明</li>"""))
        assertEquals("东10-625", parser.room("""<li class="list-group-title">东10-625空调</li>"""))
        assertEquals("东10-625", parser.room("""<li class="list-group-title"> 东10-625 </li>"""))
        // A title that is only the meter type is kept, and an empty one stays null.
        assertEquals("照明", parser.room("""<li class="list-group-title">照明</li>"""))
        assertNull(parser.room("""<li class="list-group-title"></li>"""))
        assertNull(parser.room("<p>没有标题</p>"))
    }

    @Test fun readsTimestampsAsBeijingTime() {
        HandoffFixtures.expected.getAsJsonArray("timestamps").forEach { element ->
            val expected = element.asJsonObject
            val actual = parser.timestamp(expected.get("text").asString)
            if (expected.get("epoch").isJsonNull) {
                assertNull("${expected.get("text").asString} 不是合法时间", actual)
            } else {
                assertEquals(expected.get("epoch").asLong, actual!!.epochSecond)
            }
        }
    }

    private fun assertMeters(expected: com.google.gson.JsonObject, actual: List<com.zebwqfox.hbustpower.model.MeterStatus>) {
        val expectedMeters = expected.getAsJsonArray("meters")
        assertEquals(expectedMeters.size(), actual.size)
        expectedMeters.forEachIndexed { index, element ->
            val meter = element.asJsonObject
            assertEquals(meter.get("name").asString, actual[index].name)
            assertEquals(meter.get("powerStatus").asString, actual[index].powerStatus)
            assertEquals(meter.get("communicationStatus").asString, actual[index].communicationStatus)
        }
    }
}
