package com.zebwqfox.hbustpower

import com.google.gson.JsonArray
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import java.nio.file.Files
import java.nio.file.Path

/**
 * The handoff package's `fixtures/` directory sits above the Gradle project, so tests walk up to
 * find it rather than duplicating the samples into test resources.
 */
object HandoffFixtures {
    private val root: Path by lazy {
        var current = Path.of(System.getProperty("user.dir")).toAbsolutePath()
        repeat(4) {
            if (Files.exists(current.resolve("fixtures/home.html"))) return@lazy current
            current = current.parent
        }
        error("找不到交接包 fixtures 目录")
    }

    fun html(name: String): String = Files.readString(root.resolve("fixtures/$name"))

    fun json(name: String): JsonObject =
        JsonParser.parseString(Files.readString(root.resolve("fixtures/$name"))).asJsonObject

    fun jsonArray(name: String): JsonArray =
        JsonParser.parseString(Files.readString(root.resolve("fixtures/$name"))).asJsonArray

    /** `expected-1.7.1.json`, generated by `tools/ios-parser-harness` from the iOS 1.7.1 code. */
    val expected: JsonObject by lazy { json("expected-1.7.1.json") }
}

/** Gson maps JSON null to [com.google.gson.JsonNull]; this returns a Kotlin null instead. */
fun JsonObject.stringOrNull(key: String): String? =
    get(key)?.takeUnless { it.isJsonNull }?.asString
