# Same three commands as scripts/secrets.sh, for Windows PowerShell. Requires openssl on PATH
# (Git for Windows ships one at C:\Program Files\Git\usr\bin\openssl.exe).
param([Parameter(Mandatory = $true)][ValidateSet('unlock', 'apply', 'lock')][string]$Command)

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$plain = Join-Path $root 'secrets/secrets.env'
$cipher = Join-Path $root 'secrets/secrets.env.enc'
$encArgs = @('-aes-256-cbc', '-pbkdf2', '-iter', '200000', '-salt')

switch ($Command) {
    'unlock' {
        if (-not (Test-Path $cipher)) { throw "No $cipher yet. Create secrets.env from the example and run 'lock' first." }
        & openssl enc -d @encArgs -in $cipher -out $plain
        Write-Host "Wrote $plain"
    }
    'lock' {
        if (-not (Test-Path $plain)) { throw "Missing $plain" }
        & openssl enc @encArgs -in $plain -out $cipher
        Write-Host "Wrote $cipher - safe to commit."
    }
    'apply' {
        if (-not (Test-Path $plain)) { throw "Missing $plain. Run '$PSCommandPath unlock' first." }
        $values = @{}
        Get-Content $plain | Where-Object { $_ -match '^\s*[^#].*=' } | ForEach-Object {
            $pair = $_ -split '=', 2
            $values[$pair[0].Trim()] = $pair[1].Trim()
        }
        if (-not $values.ContainsKey('SCHOOL_APP_KEY')) { throw 'SCHOOL_APP_KEY is not set in secrets.env' }

        New-Item -ItemType Directory -Force -Path (Join-Path $root 'ios/Config') | Out-Null
        "// Generated by scripts/secrets.ps1 - do not commit.`nSCHOOL_APP_KEY = $($values['SCHOOL_APP_KEY'])" |
            Set-Content -Encoding UTF8 (Join-Path $root 'ios/Config/Secrets.xcconfig')
        "# Generated by scripts/secrets.ps1 - do not commit.`nschoolAppKey=$($values['SCHOOL_APP_KEY'])" |
            Set-Content -Encoding UTF8 (Join-Path $root 'android/secrets.properties')
        Write-Host 'Wrote ios/Config/Secrets.xcconfig and android/secrets.properties'
    }
}
