#!/usr/bin/env bash
# Manage the shared secrets: unlock, apply to both platforms, lock again.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
plain="$root/secrets/secrets.env"
cipher="$root/secrets/secrets.env.enc"
cmd="${1:-}"

enc_args=(-aes-256-cbc -pbkdf2 -iter 200000 -salt)

case "$cmd" in
unlock)
    [ -f "$cipher" ] || { echo "No $cipher yet. Create secrets.env from the example and run 'lock' first." >&2; exit 1; }
    openssl enc -d "${enc_args[@]}" -in "$cipher" -out "$plain"
    chmod 600 "$plain"
    echo "Wrote $plain"
    ;;
lock)
    [ -f "$plain" ] || { echo "Missing $plain" >&2; exit 1; }
    openssl enc "${enc_args[@]}" -in "$plain" -out "$cipher"
    echo "Wrote $cipher — safe to commit."
    ;;
apply)
    [ -f "$plain" ] || { echo "Missing $plain. Run '$0 unlock' first." >&2; exit 1; }
    # shellcheck disable=SC1090
    set -a; source "$plain"; set +a
    : "${SCHOOL_APP_KEY:?SCHOOL_APP_KEY is not set in secrets.env}"

    mkdir -p "$root/ios/Config"
    cat > "$root/ios/Config/Secrets.xcconfig" <<EOF
// Generated by scripts/secrets.sh — do not commit.
SCHOOL_APP_KEY = $SCHOOL_APP_KEY
EOF
    cat > "$root/android/secrets.properties" <<EOF
# Generated by scripts/secrets.sh — do not commit.
schoolAppKey=$SCHOOL_APP_KEY
EOF
    echo "Wrote ios/Config/Secrets.xcconfig and android/secrets.properties"
    ;;
*)
    echo "usage: $0 {unlock|apply|lock}" >&2
    exit 2
    ;;
esac
